### ISSUE TITLE
vscode-tidalcycles in Linux

### ISSUE THREAD

**Issue by willbasky** [kindohm/vscode-tidalcycles#8] opened 2018-04-23 08:39 UTC
Does it work in Linux?
If yes, then is it required setting?
```
"tidalcycles": {
        "feedbackColor": "rgba(100,250,100,0.5)",
        "ghciPath": "c:\\path\\to\\ghci.exe",
        "showOutputInConsoleChannel": false,
        "tidalBootPath": "c:\\path\\to\\file.hs",
        "useBootFileInCurrentDirectory": true
    }
```
if yes, then why does it return `unknown configuration setting`?
![screenshot_20180423_133848](https://user-images.githubusercontent.com/28530747/39115706-f612d11c-46fb-11e8-863e-c953e67c4af9.png)

**Comment by kindohm** [comment] 2018-04-23 13:09
The correct setting name is `bootTidalPath`, not _tidalBootPath_. Is that the issue?

**Comment by willbasky** [comment] 2018-04-23 13:27
Hm, after correction nothing changed. 
should i add the settings globally to `user setting` or locally to `workspace setting`?
BTW, tidalcycles underlined by a curly line in both cases. Is it mean it won`t work?

i reduced setting to
```
    "tidalcycles": {
        "ghciPath": "stack ghci",
        "showOutputInConsoleChannel": true
    }
```
and no effect.

**Comment by kindohm** [comment] 2018-04-23 13:30
The extension should still work even with the "unknown configuration setting" warning. Can you still get it to run, even with the warning?

I've seen the configuration warnings on my computer too. I've never tried to fix them, but the extension still works for me.

**Comment by willbasky** [comment] 2018-04-23 13:34
Ok, if it doesn`t matter, then there are something else that rest me without tidal working.
Is it restrict required to add configuration or can it works without setting?

**Comment by kindohm** [comment] 2018-04-23 13:37
Hmm, I'm not sure what will happen if you don't use any configuration settings.

Can you paste any exact errors you are seeing?

**Comment by willbasky** [comment] 2018-04-23 13:50
User setting is
```
    "tidalcycles": {
        "ghciPath": "stack ghci",
        "showOutputInConsoleChannel": true,
    }
```
after `Shift+Enter`  to evalulate a single line
output shows: `Using default Tidal package boot. `
problem shows: `Unknown configuration setting`
no sound.

For example, atom returns sound.

**Comment by kindohm** [comment] 2018-04-24 02:11
@Metaxi I saw your message on talk.lurk.org. this error that you posted is important: 

`error: Cannot read property '0' of undefined`

I think I know what the problem is, and there is probably a bug I need to fix. I'm guessing you don't have a "folder" or "project" open. You probably only have a single file. I think there is a bug where if a folder isn't being used for the editor then it crashes the plugin. I will need to take a look later.

**Comment by willbasky** [comment] 2018-04-24 06:40
@kindohm That was the error of @digitalohm, but after changing setting it disappeared.

I have no stack project for tidal, but i open folder first, then i open file. Here is screenshot with all conditions simultaneously. 
![screenshot_20180424_113329](https://user-images.githubusercontent.com/28530747/39170205-22d9f24e-47b4-11e8-84c7-90312450d2bf.png)

**Comment by kindohm** [comment] 2018-05-14 18:34
@willbasky can you update the extension and see if it works now? I've added improvements for configuration setting support, and better error handling if boot files cannot be found.

You can use the extension without any configuration settings.

**Comment by willbasky** [comment] 2018-05-15 07:51
There is still no sound.
Output is `Using default Tidal package boot. `
I changed one set: `"tidalcycles.ghciPath": "stack ghci"` and nothing.

I use `stack ghci` in my system and have no any `ghc` installed. Setting `stack ghci` works for Atom within `ghciPath` well.
Maybe `vscode-tidalcycles` requires just `ghc` and can`t parse `stack ghci`?

**Comment by kindohm** [comment] 2018-06-13 14:16
it's working for me on a linux VM. it's the default extension configuration and I made no changes:

![image](https://user-images.githubusercontent.com/9797/41356886-797f837c-6eea-11e8-8e3d-c55dfdc3beb4.png)

**Comment by willbasky** [comment] 2018-06-14 07:26
#9 it works with this code.

**Comment by kindohm** [comment] 2018-06-14 13:35
thank you @willbasky I will close this issue once the new extension is published

**Comment by slckl** [comment] 2018-08-19 18:38
hi, 
ran into the same issue, but I see that the extension has not been updated on the marketplace, yet. I feel bad about asking, but any timelines for this?
vs code is much nicer than atom...

**Comment by kindohm** [comment] 2018-08-20 13:21
@slckl @willbasky sorry for the delay. published just now.

**Closed as completed by kindohm** 2018-08-20 13:21 UTC
